citrus_trade:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: gylobbh-fi81452
      user: DBT_USER
      password: dbt_user*A123
      role: ACCOUNTADMIN
      database: TRADE_FLOW
      warehouse: COMPUTE_WH
      schema: ANALYTICS
      threads: 4
