CREATE USER TERRAFORM_USER
PASSWORD = 'terraform_user*A123'
DEFAULT_ROLE = SYSADMIN
MUST_CHANGE_PASSWORD = FALSE
COMMENT = 'User created for Terraform provisioning and automation.';

GRANT ROLE ACCOUNTADMIN TO USER TERRAFORM_USER;
GRANT ROLE SYSADMIN TO USER TERRAFORM_USER;
GRANT ROLE SECURITYADMIN TO USER TERRAFORM_USER;


GRANT CREATE USER ON ACCOUNT TO ROLE SYSADMIN;
GRANT CREATE ROLE ON ACCOUNT TO ROLE SYSADMIN;